package models.enums.event;

public enum EventType {
    SEND_PUBLIC_MESSAGE,
    PRIVATE_MESSAGE_SEND,
    PUBLIC_MESSAGE_RECEIVE,
    PRIVATE_MESSAGE_RECEIVE,
    DISCOVER,
    SEND_HELLO,
    PROGRAM_START,
    GET_MESSAGE_HISTORY,
    SEND_CONACK,
    SEND_CONREQ,
    GET_PEER_LIST,
    ADD_PEER,
    CONNECTION_REQUESTED,
    ADD_MESSAGE_TO_HISTORY,
    PROGRAM_END, HANDLE_PUBLIC_MESSAGE,
    ADD_PRIVATE_MESSAGE_TO_HISTORY,
    GET_LOCAL_PEER, IS_PEER_CONNECTED, GET_PEER, REMOVE_PEER, GET_LOCAL_PEER_ID
}
